# Generated by Django 4.0.6 on 2022-08-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_advuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Аватарка'),
        ),
    ]
