# Generated by Django 4.0.6 on 2022-08-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rubric_subrubricmanager_superrubricmanager_subrubric_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubRubricManager',
        ),
        migrations.DeleteModel(
            name='SuperRubricManager',
        ),
    ]
