# Generated by Django 4.0.6 on 2022-08-06 17:11

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_additionalimage_image_alter_bb_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='images',
            field=models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Основное изображение'),
        ),
    ]
