# Generated by Django 4.0.6 on 2022-08-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_advuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='name',
        ),
    ]
