# Generated by Django 4.0.6 on 2022-08-05 10:42

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bb_additionalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to=main.utilities.get_timestamp_path, verbose_name='Доп. фото'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Сделать товар видимым?'),
        ),
    ]
