# Generated by Django 4.0.6 on 2022-08-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_advuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
