# Generated by Django 4.0.6 on 2022-08-17 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_advuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='main.subrubric', verbose_name='Рубрика'),
        ),
    ]
