version: "3.9"

services:
  web:
    build: .
    environment:
      MYENV: EXAMPLE
    volumes:
      - .:/code
  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  celery:
    build: .
    command: celery -A config worker -l INFO
    volumes:
        - .:/code
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web_run
      - web
      - redis
  redis:
    image: "redis:alpine"
